name: "docker-push"

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Bygg Docker image
        uses: docker/build-push-action@v2
        with:
          tags: "ghcr.io/bjornsnoen/minica-traefik-api:latest"
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
